// // RootLayout.tsx

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { SessionProvider } from "next-auth/react";
// import dynamic from "next/dynamic";
// const QueryClientProvider = dynamic(() => import("./QueryClientProvider"));

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "KMC-Dashboard",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <QueryClientProvider>
//           {/* <SessionProvider session={undefined}> */}{" "}
//           {/* Pass undefined session to avoid SSR */}
//           {children}
//           {/* </SessionProvider> */}
//         </QueryClientProvider>
//       </body>
//     </html>
//   );
// }

"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "./QueryClientProvider";
import AuthContext from "./api/auth/AuthContext";
import { SessionProvider, useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "KMC-Dashboard",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <AuthContext>
            <QueryClientProvider>{children}</QueryClientProvider>
          </AuthContext>
        </SessionProvider>
      </body>
    </html>
  );
}
